using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using CommunityToolkit.Mvvm.ComponentModel;
using Digi21.WinUI.PropertyGrid;

namespace PropertyGridGallery;

// An ObservableObject from the toolkit, with no glue at all: the grid only ever looks for
// INotifyPropertyChanged, which is what ObservableObject implements. Any other MVVM library, or a
// hand-rolled implementation, works exactly the same way.
//
// The properties are written out rather than generated by [ObservableProperty] so the attributes
// the grid reads sit where you would expect to find them.
public class SampleModel : ObservableObject
{
    private string name = "Parcels";
    private string notes = "Cadastral parcels, revision of 2026." + "\r\n"
        + "Three lines, so the row has to grow to fit the editor rather than clipping it.";
    private Guid internalId = Guid.NewGuid();
    private int opacity = 80;
    private bool isVisible = true;
    private bool? isLocked;
    private LineStyle outline = LineStyle.Solid;
    private Interactions interactions = Interactions.Select | Interactions.Hover;
    private double minimumScale = 1000.5;
    private decimal featureCount = 9007199254740993m;
    private double area = 1234.56;
    private Uri? source = new("https://example.com/parcels.gpkg");
    private string sourceFile = @"C:\data\parcels.gpkg";
    private DirectoryInfo? exportFolder = new(@"C:\data\exports");
    private DateTime updatedAt = new(2026, 8, 13, 9, 30, 0, DateTimeKind.Local);
    private DateOnly surveyedOn = new(2026, 3, 1);
    private TimeSpan refreshEvery = TimeSpan.FromMinutes(90);
    private Windows.UI.Color fill = Microsoft.UI.Colors.CornflowerBlue;
    private string tag = string.Empty;

    [Category("Identity")]
    [DisplayName("Layer name")]
    [Description("What this layer is called in the legend.")]
    [PropertyOrder(0)]
    [Required]
    [StringLength(40, MinimumLength = 2)]
    public string Name
    {
        get => name;
        set => SetProperty(ref name, value);
    }

    [Category("Identity")]
    [Description("A longer note about what the layer holds.")]
    [DataType(DataType.MultilineText)]
    public string Notes
    {
        get => notes;
        set => SetProperty(ref notes, value);
    }

    [Category("Identity")]
    [Browsable(false)]
    public Guid InternalId
    {
        get => internalId;
        set => SetProperty(ref internalId, value);
    }

    [Category("Appearance")]
    [Description("How opaque the layer is drawn, from nothing to fully solid.")]
    [Range(0, 100)]
    public int Opacity
    {
        get => opacity;
        set => SetProperty(ref opacity, value);
    }

    [Category("Appearance")]
    [Description("Whether the layer is drawn at all.")]
    [DefaultValue(true)]
    public bool IsVisible
    {
        get => isVisible;
        set => SetProperty(ref isVisible, value);
    }

    [Category("Appearance")]
    [Description("Left unset until somebody decides, which is what the third state of the box means.")]
    public bool? IsLocked
    {
        get => isLocked;
        set => SetProperty(ref isLocked, value);
    }

    [Category("Appearance")]
    [Description("How the outline of each parcel is drawn.")]
    public LineStyle Outline
    {
        get => outline;
        set => SetProperty(ref outline, value);
    }

    [Category("Appearance")]
    [Description("Which parts of the layer respond to the pointer.")]
    public Interactions Interactions
    {
        get => interactions;
        set => SetProperty(ref interactions, value);
    }

    [Category("Geometry")]
    [Description("The scale the layer stops being drawn below.")]
    public double MinimumScale
    {
        get => minimumScale;
        set => SetProperty(ref minimumScale, value);
    }

    [Category("Geometry")]
    [Description("How many features the layer holds. A decimal, so it gets the text editor: a number box works in doubles and would round this one.")]
    public decimal FeatureCount
    {
        get => featureCount;
        set => SetProperty(ref featureCount, value);
    }

    [Category("Geometry")]
    [ReadOnly(true)]
    [Description("Computed from the geometry, so the grid will not write it.")]
    public double Area
    {
        get => area;
        set => SetProperty(ref area, value);
    }

    [Category("Source")]
    [Description("Where the data was loaded from.")]
    public Uri? Source
    {
        get => source;
        set => SetProperty(ref source, value);
    }

    [Category("Source")]
    [FilePath(FilePathKind.OpenFile, ".gpkg", ".las")]
    [Description("The file on disk. The button asks the application to browse; the grid never opens a dialog itself.")]
    public string SourceFile
    {
        get => sourceFile;
        set => SetProperty(ref sourceFile, value);
    }

    [Category("Source")]
    [Description("Where exports are written. A DirectoryInfo, so it gets the browse button without the attribute.")]
    public DirectoryInfo? ExportFolder
    {
        get => exportFolder;
        set => SetProperty(ref exportFolder, value);
    }

    [Category("Source")]
    [Description("When the layer was last refreshed.")]
    public DateTime UpdatedAt
    {
        get => updatedAt;
        set => SetProperty(ref updatedAt, value);
    }

    [Category("Source")]
    [Description("The day the ground truth was collected. A DateOnly, so it gets a calendar and no clock.")]
    public DateOnly SurveyedOn
    {
        get => surveyedOn;
        set => SetProperty(ref surveyedOn, value);
    }

    [Category("Source")]
    [Description("How often the layer is refreshed. A duration, so it gets a text box: a clock cannot express more than a day.")]
    public TimeSpan RefreshEvery
    {
        get => refreshEvery;
        set => SetProperty(ref refreshEvery, value);
    }

    [Category("Appearance")]
    [Description("The colour parcels are filled with.")]
    public Windows.UI.Color Fill
    {
        get => fill;
        set => SetProperty(ref fill, value);
    }

    [Category("Source")]
    [Expandable]
    [Description("The server the layer comes from. Open it to edit its fields in place.")]
    public ServerSettings Server { get; } = new();

    [Category("Appearance")]
    [Description("The scales the layer is drawn at. A list, so it gets a summary and a button that asks the application to edit it.")]
    public IList<int> Scales { get; } = [500, 1000, 5000];

    // No category, so it lands in Misc - which sorts last however the grid is arranged.
    [Description("Anything the application wants to hang off the layer.")]
    public string Tag
    {
        get => tag;
        set => SetProperty(ref tag, value);
    }
}

public class ServerSettings : ObservableObject
{
    private string host = "tiles.example.com";
    private int port = 443;
    private bool useTls = true;

    [Description("The host to connect to.")]
    public string Host
    {
        get => host;
        set => SetProperty(ref host, value);
    }

    [Description("The port to connect on.")]
    [Range(1, 65535)]
    public int Port
    {
        get => port;
        set => SetProperty(ref port, value);
    }

    [Description("Whether the connection is encrypted.")]
    public bool UseTls
    {
        get => useTls;
        set => SetProperty(ref useTls, value);
    }
}

public enum LineStyle
{
    Solid,

    [Display(Name = "Dashed line")]
    Dashed,

    [Description("Short dots, for hairline boundaries.")]
    Dotted,
}

[Flags]
public enum Interactions
{
    None = 0,
    Select = 1,
    Hover = 2,
    Edit = 4,
}
